# CMAKE generated file: DO NOT EDIT!
# Generated by "MinGW Makefiles" Generator, CMake Version 3.20

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

SHELL = cmd.exe

# The CMake executable.
CMAKE_COMMAND = "C:\Program Files\JetBrains\CLion 2021.2.2\bin\cmake\win\bin\cmake.exe"

# The command to remove a file.
RM = "C:\Program Files\JetBrains\CLion 2021.2.2\bin\cmake\win\bin\cmake.exe" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = C:\Users\Rafac\Desktop\TP_POO_2021_2022

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = C:\Users\Rafac\Desktop\TP_POO_2021_2022

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	"C:\Program Files\JetBrains\CLion 2021.2.2\bin\cmake\win\bin\cmake.exe" -E echo "No interactive CMake dialog available."
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	"C:\Program Files\JetBrains\CLion 2021.2.2\bin\cmake\win\bin\cmake.exe" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Rafac\Desktop\TP_POO_2021_2022\CMakeFiles C:\Users\Rafac\Desktop\TP_POO_2021_2022\\CMakeFiles\progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start C:\Users\Rafac\Desktop\TP_POO_2021_2022\CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named TP_POO_2021_2022

# Build rule for target.
TP_POO_2021_2022: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles\Makefile2 TP_POO_2021_2022
.PHONY : TP_POO_2021_2022

# fast build rule for target.
TP_POO_2021_2022/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/build
.PHONY : TP_POO_2021_2022/fast

config.obj: config.cpp.obj
.PHONY : config.obj

# target to build an object file
config.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/config.cpp.obj
.PHONY : config.cpp.obj

config.i: config.cpp.i
.PHONY : config.i

# target to preprocess a source file
config.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/config.cpp.i
.PHONY : config.cpp.i

config.s: config.cpp.s
.PHONY : config.s

# target to generate assembly for a file
config.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/config.cpp.s
.PHONY : config.cpp.s

edificio.obj: edificio.cpp.obj
.PHONY : edificio.obj

# target to build an object file
edificio.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/edificio.cpp.obj
.PHONY : edificio.cpp.obj

edificio.i: edificio.cpp.i
.PHONY : edificio.i

# target to preprocess a source file
edificio.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/edificio.cpp.i
.PHONY : edificio.cpp.i

edificio.s: edificio.cpp.s
.PHONY : edificio.s

# target to generate assembly for a file
edificio.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/edificio.cpp.s
.PHONY : edificio.cpp.s

ilha.obj: ilha.cpp.obj
.PHONY : ilha.obj

# target to build an object file
ilha.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/ilha.cpp.obj
.PHONY : ilha.cpp.obj

ilha.i: ilha.cpp.i
.PHONY : ilha.i

# target to preprocess a source file
ilha.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/ilha.cpp.i
.PHONY : ilha.cpp.i

ilha.s: ilha.cpp.s
.PHONY : ilha.s

# target to generate assembly for a file
ilha.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/ilha.cpp.s
.PHONY : ilha.cpp.s

main.obj: main.cpp.obj
.PHONY : main.obj

# target to build an object file
main.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/main.cpp.obj
.PHONY : main.cpp.obj

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/main.cpp.s
.PHONY : main.cpp.s

trabalhador.obj: trabalhador.cpp.obj
.PHONY : trabalhador.obj

# target to build an object file
trabalhador.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/trabalhador.cpp.obj
.PHONY : trabalhador.cpp.obj

trabalhador.i: trabalhador.cpp.i
.PHONY : trabalhador.i

# target to preprocess a source file
trabalhador.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/trabalhador.cpp.i
.PHONY : trabalhador.cpp.i

trabalhador.s: trabalhador.cpp.s
.PHONY : trabalhador.s

# target to generate assembly for a file
trabalhador.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/trabalhador.cpp.s
.PHONY : trabalhador.cpp.s

zona.obj: zona.cpp.obj
.PHONY : zona.obj

# target to build an object file
zona.cpp.obj:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/zona.cpp.obj
.PHONY : zona.cpp.obj

zona.i: zona.cpp.i
.PHONY : zona.i

# target to preprocess a source file
zona.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/zona.cpp.i
.PHONY : zona.cpp.i

zona.s: zona.cpp.s
.PHONY : zona.s

# target to generate assembly for a file
zona.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles\TP_POO_2021_2022.dir\build.make CMakeFiles/TP_POO_2021_2022.dir/zona.cpp.s
.PHONY : zona.cpp.s

# Help Target
help:
	@echo The following are some of the valid targets for this Makefile:
	@echo ... all (the default if no target is provided)
	@echo ... clean
	@echo ... depend
	@echo ... edit_cache
	@echo ... rebuild_cache
	@echo ... TP_POO_2021_2022
	@echo ... config.obj
	@echo ... config.i
	@echo ... config.s
	@echo ... edificio.obj
	@echo ... edificio.i
	@echo ... edificio.s
	@echo ... ilha.obj
	@echo ... ilha.i
	@echo ... ilha.s
	@echo ... main.obj
	@echo ... main.i
	@echo ... main.s
	@echo ... trabalhador.obj
	@echo ... trabalhador.i
	@echo ... trabalhador.s
	@echo ... zona.obj
	@echo ... zona.i
	@echo ... zona.s
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles\Makefile.cmake 0
.PHONY : cmake_check_build_system

